.PHONY: clean

h7-3: h7-3.cc
	g++ h7-3.cc -std=c++14 -g -ggdb -o h7-3
h7-2: h7-2.cc
	g++ h7-2.cc -std=c++14 -g -ggdb -o h7-2
h7-1: h7-1.cc
	g++ h7-1.cc -std=c++14 -g -ggdb -o h7-1

clean:
	@echo cleaning
	@rm -f h7-1 a.out
